# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86b0a3c7b34cf2f8c91710142cb333e7c735cb752c1131e94672bcaec3a66021829c212dc007ddda6814e3d2f4eec926b5ec9959e6717d467b28e83ba9b5f60f

test:
  secret_key_base: 0fb2eb88800d084019487c2dac2c3bda98b8aaa1d72fa284b298bd6a576c0af9a68a0287394ced06b2c8a45760045b1d64ae7e999c273b7aefcc2977a0ad5954

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
